server:
  servlet:
    encoding:
      enable: true
      charset: UTF-8
      force: true
  port: 8080
spring:
  application:
    name: spring-ai
  ai:
    ollama:
      base-url: http://localhost:11434